package weather-py:provider;

/// MCP tools for An MCP server written in Python
world weather-py {
    import wasi:http/outgoing-handler@0.2.3;
    export wasmcp:mcp/core-capabilities@0.2.0-alpha.6;
    export wasmcp:mcp/tools-capabilities@0.2.0-alpha.6;
}