package {{project-name}}:provider;

/// MCP tools for {{project-name}}
world {{project-name}} {
    import wasi:http/outgoing-handler@0.2.3;
    export wasmcp:mcp/core-capabilities@0.1.0;
    export wasmcp:mcp/tools-capabilities@0.1.0;
}