package wasmcp:handler;

world handler {
  export mcp;
}

interface mcp {
  list-tools: func() -> string;
  call-tool: func(name: string, arguments: string) -> string;
  list-resources: func() -> string;
  read-resource: func(uri: string) -> string;
  list-prompts: func() -> string;
  get-prompt: func(name: string, arguments: string) -> string;
}