package {{project-name | kebab_case}}:capabilities;

world {{project-name | kebab_case}} {
    export wasmcp:mcp/lifecycle@0.2.0;
    export wasmcp:mcp/authorization@0.2.0;
    export wasmcp:mcp/tools@0.2.0;
}