package wasmcp:writer@0.1.0;

world writer {
    import wasmcp:mcp/message-writer@0.3.1-alpha.25;
    export wasmcp:mcp/notifications-writer@0.3.1-alpha.25;
    export wasmcp:mcp/error-writer@0.3.1-alpha.25;
    export wasmcp:mcp/lifecycle-writer@0.3.1-alpha.25;
    export wasmcp:mcp/tools-writer@0.3.1-alpha.25;
    export wasmcp:mcp/resources-writer@0.3.1-alpha.25;
    export wasmcp:mcp/prompts-writer@0.3.1-alpha.25;
    export wasmcp:mcp/completions-writer@0.3.1-alpha.25;
}
