package {{project-name | kebab_case}}:provider;

/// MCP provider for {{project-name | kebab_case}}
world {{project-name | kebab_case}} {
    import wasi:http/outgoing-handler@0.2.3;
    export wasmcp:mcp/lifecycle@0.2.0;
    export wasmcp:mcp/authorization@0.2.0;
    export wasmcp:mcp/tools@0.2.0;
}