[workspace]

[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen-rt = { version = "0.44.0", features = ["bitflags"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:rust"

[package.metadata.component.target]
path = "wit"
world = "tools-handler"

[package.metadata.component.target.dependencies]
"wasmcp:mcp" = { version = "0.3.0" }
