// Code generated by wit-bindgen-go. DO NOT EDIT.

package handler

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "wasmcp:mcp/handler@0.1.0".
var Exports struct {
	// ListTools represents the caller-defined, exported function "list-tools".
	//
	//	list-tools: func() -> list<tool>
	ListTools func() (result cm.List[Tool])

	// CallTool represents the caller-defined, exported function "call-tool".
	//
	//	call-tool: func(name: string, arguments: string) -> tool-result
	CallTool func(name string, arguments string) (result ToolResult)

	// ListResources represents the caller-defined, exported function "list-resources".
	//
	//	list-resources: func() -> list<resource-info>
	ListResources func() (result cm.List[ResourceInfo])

	// ReadResource represents the caller-defined, exported function "read-resource".
	//
	//	read-resource: func(uri: string) -> resource-result
	ReadResource func(uri string) (result ResourceResult)

	// ListPrompts represents the caller-defined, exported function "list-prompts".
	//
	//	list-prompts: func() -> list<prompt>
	ListPrompts func() (result cm.List[Prompt])

	// GetPrompt represents the caller-defined, exported function "get-prompt".
	//
	//	get-prompt: func(name: string, arguments: string) -> prompt-result
	GetPrompt func(name string, arguments string) (result PromptResult)
}
