package weather-js:provider;

/// MCP tools for weather-js
world weather-js {
    import wasi:http/outgoing-handler@0.2.3;
    export fastertools:mcp/core-capabilities@0.4.0;
    export fastertools:mcp/tools-capabilities@0.4.0;
}