package wasmcp:kv-store@0.1.0;

world kv-store {
    import wasi:keyvalue/store@0.2.0-draft;
    import wasi:keyvalue/batch@0.2.0-draft;
    import wasi:keyvalue/atomics@0.2.0-draft;

    export wasmcp:keyvalue/store@0.1.0;
}
