use anyhow::Result;
use serde_json::{json, Value};
use spin_sdk::http::{IntoResponse, Request, Response, Method};
use jsonwebtoken::errors::ErrorKind;
use jsonwebtoken::{decode, encode, Algorithm, DecodingKey, EncodingKey, Header, Validation};

// Bindings are generated by cargo-component
#[allow(warnings)]
mod bindings;

use bindings::wasmcp::mcp::oauth2_protected_resource::{get_protected_resource_metadata};
use bindings::wasmcp::mcp::jwt_validation::{get_validation_config};
use bindings::wasmcp::mcp::jwks_cache::{get_jwks_uri};

mod capabilities;
mod auth;
mod error;
mod constants;
use error::{ErrorCode, ErrorCodeExt, McpError};
use constants::{methods, routes};


#[spin_sdk::http_component]
async fn handle_request(req: Request) -> Result<impl IntoResponse> {
    let method = req.method();
    let path: &str = req.path();

    // Handle the [RFC9728] 3.1. Protected Resource Metadata Request
    //
    // https://datatracker.ietf.org/doc/html/rfc9728#name-protected-resource-metadata-
    // https://modelcontextprotocol.io/specification/2025-06-18/basic/authorization#authorization-server-location
    if method == &Method::Get && path == routes::WELL_KNOWN_RESOURCE_METADATA {
        let meta = get_protected_resource_metadata();
        return Ok(Response::builder()
            .status(200)
            .header("content-type", "application/json")
            .body(json!({
                "resource": meta.resource,
                "authorization_servers": meta.authorization_servers,
            }).to_string())
            .build());
    }


    // Reject anything else but *the MCP endpoint*
    //
    // https://modelcontextprotocol.io/specification/2025-06-18/basic/transports#streamable-http
    if !(method == &Method::Post && path == routes::MCP) {
        return Ok(Response::builder()
            .status(404)
            .header("content-type", "application/json")
            .body(json!({
                "error": "Not Found"
            }).to_string())
            .build());
    }

    //const WWW_AUTHENTICATE_HEADER = [
//   'Bearer error="unauthorized"',
//   'error_description="Authorization needed"',
//   `resource_metadata="https://mcp.example.com/.well-known/oauth-protected-resource"`,
// ].join(', ');

    // Authorize the request
    // Include WWW-Authenticate header on 401 Unauthorized responses
    //
    // https://datatracker.ietf.org/doc/html/rfc9728#name-www-authenticate-response
    // https://modelcontextprotocol.io/specification/2025-06-18/basic/authorization#authorization-server-location
    match auth::authorize_request(&req).await {
                Ok(context) => context,
                // TODO: Need to take resource from get_protected_resource_metadata() and use it to populate the WWW-Authenticate header
                Err(auth_error) => return Ok(Response::builder()
                .status(401)
                .header("content-type", "application/json")
                .header("WWW-Authenticate",
                    vec![
                        "Bearer error=\"unauthorized\"", "error_description=\"Authorization needed\"",
                        &format!("resource_metadata=\"{}/{}\"",
                        // BELOW IS BAD because mcp spec says resoruce can be more specific even like /mcp so wouldn't work like this.
                        // We need to add an explicity get-www-authenticate-header() function to the oauth2-protected-resource WIT interface.
                        get_protected_resource_metadata().resource, routes::WELL_KNOWN_RESOURCE_METADATA)
                    ].join(", ")
                )
                .build()),
    }

    // let provider_config = auth::get_auth_config()
    //     .as_ref()
    //     .expect("auth is enabled but config is None");
        
    //     match auth::authorize_request(&req, provider_config).await {
    //         Ok(context) => context,
    //         Err(auth_error) => return Ok(auth::create_auth_error_response(auth_error)),
    //     }

    // Handle standard JSON-RPC endpoint
    let body = req.body();
    let request_str = std::str::from_utf8(body)?;

    // Parse JSON-RPC request
    let json_request: Value = serde_json::from_str(request_str)?;

    // Extract method and params
    let method = json_request["method"]
        .as_str()
        .ok_or_else(|| anyhow::anyhow!("Missing method"))?;
    let params = json_request.get("params").cloned();
    let id = json_request.get("id").cloned();

    // Route to appropriate handler
    match route_method(method, params, context).await {
        Ok(result) => {
            let response = if let Some(id) = id {
                json!({
                    "jsonrpc": "2.0",
                    "result": result,
                    "id": id
                })
            } else {
                // Notification (no id) - no response expected
                return Ok(Response::builder()
                    .status(204)
                    .header("content-type", "application/json")
                    .body(())
                    .build());
            };

            Ok(Response::builder()
                .status(200)
                .header("content-type", "application/json")
                .body(response.to_string())
                .build())
        }
        Err(error) => {
            let error_response = json!({
                "jsonrpc": "2.0",
                "error": {
                    "code": error.code.to_code(),
                    "message": error.message,
                    "data": error.data
                },
                "id": id
            });

            Ok(Response::builder()
                .status(200)
                .header("content-type", "application/json")
                .body(error_response.to_string())
                .build())
        }
    }
}

/// Route method calls to appropriate handlers
/// Auth context is None if auth is disabled by provider
async fn route_method(
    method: &str,
    params: Option<Value>,
    auth_context: Option<AuthContext>,
) -> Result<Value, McpError> {
    match method {
        // Core lifecycle methods - always available
        methods::INITIALIZE => capabilities::lifecycle::initialize(params),
        methods::INITIALIZED => capabilities::lifecycle::client_initialized(),
        methods::PING => Ok(json!({})), // Simple ping response
        methods::SHUTDOWN => capabilities::lifecycle::shutdown(),

        // Tools methods - only if feature enabled
        #[cfg(feature = "tools")]
        methods::TOOLS_LIST => capabilities::tools::list_tools(params),
        #[cfg(feature = "tools")]
        methods::TOOLS_CALL => capabilities::tools::call_tool(params, auth_context.as_ref()),

        // Resources methods - only if feature enabled
        #[cfg(feature = "resources")]
        methods::RESOURCES_LIST => capabilities::resources::list_resources(params),
        #[cfg(feature = "resources")]
        methods::RESOURCES_READ => capabilities::resources::read_resource(params),

        // Prompts methods - only if feature enabled
        #[cfg(feature = "prompts")]
        methods::PROMPTS_LIST => capabilities::prompts::list_prompts(params),
        #[cfg(feature = "prompts")]
        methods::PROMPTS_GET => capabilities::prompts::get_prompt(params),

        // Completion methods - only if feature enabled
        #[cfg(feature = "completion")]
        methods::COMPLETION_COMPLETE => capabilities::completion::complete(params),

        _ => Err(McpError {
            code: ErrorCode::MethodNotFound,
            message: format!("Method '{method}' not found"),
            data: None,
        }),
    }
}