package wasmcp:hash;

/// MCP tools for An MCP server written in Go
world hash {
    /// TinyGo requires WASI CLI imports for wasip2 target
    include wasi:cli/imports@0.2.3;
    
    /// Export MCP core capabilities for auth configuration
    export wasmcp:mcp/tools-capability@0.4.0;
}