[package]
name = "context-provider"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { version = "0.36", features = ["default"] }
hex = "0.4"

[profile.release]
opt-level = "z"
lto = true
strip = true