package weather-ts:provider;

/// MCP provider for weather-ts
world weather-ts {
    import wasi:http/outgoing-handler@0.2.3;
    export wasmcp:mcp/lifecycle@0.2.0;
    export wasmcp:mcp/authorization@0.2.0;
    export wasmcp:mcp/tools@0.2.0;
}