// Code generated by wit-bindgen-go. DO NOT EDIT.

package handler

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// ErrorShape is used for storage in variant or result types.
type ErrorShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(Error{})]byte
}

// ResourceContentsShape is used for storage in variant or result types.
type ResourceContentsShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(ResourceContents{})]byte
}
