package {{project-name | kebab_case}}:provider;

/// MCP tools for {{project-description}}
world {{project-name | kebab_case}} {
    import wasi:http/outgoing-handler@0.2.3;
    export fastertools:mcp/tools-capabilities@0.1.12;
}