package wasmcp:transport@0.2.0;

/// Provides a standardized way for servers to offer argument autocompletion suggestions for prompts and resource URIs
///
/// https://modelcontextprotocol.io/specification/2025-06-18/server/utilities/completion
interface completion {
    use wasmcp:mcp/mcp-types@0.2.0.{mcp-error};
    use wasmcp:mcp/completion-types@0.2.0.{complete-request, complete-result};

    /// Handle request for completion suggestions
    complete: func(request: complete-request) -> result<complete-result, mcp-error>;
}