interface context {
    use types.{alist};

    record request {
        id: u16,
        method: string,
        headers: alist,
    }

    resource context {
        constructor(request: request);
        get-request: func() -> request;

        get-header: func(key: string) -> option<string>;
        set-header: func(key: string, value: string);
        delete-header; func(key: string);
        list-header-keys: func() -> list<string>;

        get-state: func(key: string) -> option<string>;
        set-state: func(key: string, value: string);
        delete-state: func(key: string);
        list-state-keys: func() -> list<string>;
    }
}

interface session-context {
    use context.{context};

    session-get(ctx: borrow<context>, key: string) -> result<option<string>>;
    session-set(ctx: borrow<context>, key: string, value: string) -> result;
    session-delete(ctx: borrow<context>, key: string) -> result;
    session-list-keys(ctx: borrow<context>) -> result<list<string>>
}

interface claims-context {
    use context.{context};
    use validation.{claims};

    claims-get(ctx: borrow<context>) -> result<claims>;
}
