interface initialize {
    use request.{context};
    use methods.{initialize-params}
    use messages.{initialize-result, mcp-error};
    
    /// Describes the server and its capabilities to a client
    initialize: func(ctx: borrow<context>, params: initialize-params) -> result<initialize-result, mcp-error>;
}
