interface claims {
    type extras = list<tuple<string, string>>;

    record claims {
        /// Expiration time (as UTC timestamp)
        exp: u64,
        /// Audience
        aud: option<string>,
        /// Issued at (as UTC timestamp)
        iat: option<u64>,
        /// Issuer
        iss: option<string>,
        /// Not Before (as UTC timestamp)
        nbf: option<u64>,
        /// Subject (whom token refers to)
        sub: option<string>,
        /// Extra claims as an association list
        extras: option<extras>,
    }

    /// Validation error types
    variant validation-error {
        /// When a token doesn't have a valid JWT shape
        invalid-token,
        /// When the signature doesn't match
        invalid-signature,
        /// When the secret given is not a valid ECDSA key
        invalid-ecdsa-key,
        /// When the secret given is not a valid RSA key
        invalid-rsa-key,
        /// We could not sign with the given key
        rsa-failed-signing,
        /// When the algorithm from string doesn't match the one passed to `from_str`
        invalid-algorithm-name,
        /// When a key is provided with an invalid format
        invalid-key-format,

        // Validation errors
        /// When a claim required by the validation is not present
        missing-required-claim,
        /// When a token’s `exp` claim indicates that it has expired
        expired-signature,
        /// When a token’s `iss` claim does not match the expected issuer
        invalid-issuer,
        /// When a token’s `aud` claim does not match one of the expected audience values
        invalid-audience,
        /// When a token’s `sub` claim does not match one of the expected subject values
        invalid-subject,
        /// When a token’s `nbf` claim represents a time in the future
        immature-signature,
        /// When the algorithm in the header doesn't match the one passed to `decode` or the encoding/decoding key
        /// used doesn't match the alg requested
        invalid-algorithm,
        /// When the Validation struct does not contain at least 1 algorithm
        missing-algorithm,

        // 3rd party errors
        /// An error happened when decoding some base64 text
        base64,
        /// An error happened while serializing/deserializing JSON
        json,
        /// Some of the text was invalid UTF-8
        utf8,
        /// Something unspecified went wrong with crypto
        crypto,
        /// Something unspecified went wrong
        other(string),
    }    
}

/// A simple library for validating JWTs
///
/// Derived from https://github.com/Keats/jsonwebtoken
interface jwt-validator {
    use context.{context};
    use claims.{claims, extras, validation-error};

    flags required-claims {
        exp,
        nbf,
        aud,
        iss,
        sub,
    }

    enum algorithm {
        /// HMAC using SHA-256
        HS256,
        /// HMAC using SHA-384
        HS384,
        /// HMAC using SHA-512
        HS512,
        /// ECDSA using SHA-256
        ES256,
        /// ECDSA using SHA-384
        ES384,
        /// RSASSA-PKCS1-v1_5 using SHA-256
        RS256,
        /// RSASSA-PKCS1-v1_5 using SHA-384
        RS384,
        /// RSASSA-PKCS1-v1_5 using SHA-512
        RS512,
        /// RSASSA-PSS using SHA-256
        PS256,
        /// RSASSA-PSS using SHA-384
        PS384,
        /// RSASSA-PSS using SHA-512
        PS512,
        /// Edwards-curve Digital Signature Algorithm (EdDSA)
        EDDSA,
    }

    record jwk {
        kty: string,
        kid: option<string>,
        alg: option<string>,
        %use: option<string>,

        // RSA specific
        n: option<string>,
        e: option<string>,

        // HMAC specific
        k: option<string>,
    }

    /// JWKS structure for key discovery
    record jwks {
        keys: list<jwk>,
    }

    variant jwks-source {
        jwks(jwks),
        json(string),
        uri(string),
    }

    /// A basic JWT header, the alg defaults to HS256 and typ is automatically
    /// set to `JWT`. All the other fields are optional.
    record header {
        /// The type of JWS: it can only be "JWT" here
        ///
        /// Defined in [RFC7515#4.1.9](https://tools.ietf.org/html/rfc7515#section-4.1.9).
        typ: option<string>,

        /// The algorithm used
        ///
        /// Defined in [RFC7515#4.1.1](https://tools.ietf.org/html/rfc7515#section-4.1.1).
        alg: algorithm,

        /// Content type
        ///
        /// Defined in [RFC7519#5.2](https://tools.ietf.org/html/rfc7519#section-5.2).
        cty: option<string>,

        /// JSON Key URL
        ///
        jku: option<string>,

        /// JSON Web Key
        ///
        /// Defined in [RFC7515#4.1.3](https://tools.ietf.org/html/rfc7515#section-4.1.3).
        jwk: option<jwk>,

        /// Key ID
        ///
        /// Defined in [RFC7515#4.1.4](https://tools.ietf.org/html/rfc7515#section-4.1.4).
        kid: option<string>,

        /// X.509 URL
        ///
        /// Defined in [RFC7515#4.1.5](https://tools.ietf.org/html/rfc7515#section-4.1.5).
        x5u: option<string>,

        /// X.509 certificate chain. A Vec of base64 encoded ASN.1 DER certificates.
        ///
        /// Defined in [RFC7515#4.1.6](https://tools.ietf.org/html/rfc7515#section-4.1.6).
        x5c: option<list<string>>,

        /// X.509 SHA1 certificate thumbprint
        ///
        /// Defined in [RFC7515#4.1.7](https://tools.ietf.org/html/rfc7515#section-4.1.7).
        x5t: option<string>,

        /// X.509 SHA256 certificate thumbprint
        ///
        /// Defined in [RFC7515#4.1.8](https://tools.ietf.org/html/rfc7515#section-4.1.8).
        ///
        /// This will be serialized/deserialized as "x5t#S256", as defined by the RFC.
        x5t-s256: option<string>,

        /// Any additional non-standard headers not defined in [RFC7515#4.1](https://datatracker.ietf.org/doc/html/rfc7515#section-4.1).
        /// Once serialized, all keys will be converted to fields at the root level of the header payload
        /// Ex: Dict("custom" -> "header") will be converted to "{"typ": "JWT", ..., "custom": "header"}"
        extras: extras,
    }

    /// The return type of a successful validation.
    record token-data {
        /// The decoded JWT header
        header: header,
        /// The decoded JWT claims
        claims: claims,
    }

    /// Optional validations that are applied after decoding a JWT.
    ///
    /// All time validation happen on UTC timestamps as seconds.
    record validation-options {
        /// Which claims are required to be present before starting the validation.
        /// This does not interact with the various `validate_*`. If you remove `exp` from that list, you still need
        /// to set `validate_exp` to `false`.
        /// The only value that will be used are "exp", "nbf", "aud", "iss", "sub". Anything else will be ignored.
        ///
        /// Defaults to `{"exp"}`
        required-spec-claims: option<required-claims>,
        /// Add some leeway (in seconds) to the `exp` and `nbf` validation to
        /// account for clock skew.
        ///
        /// Defaults to `60`.
        leeway: option<u64>,
        /// Reject a token some time (in seconds) before the `exp` to prevent
        /// expiration in transit over the network.
        ///
        /// The value is the inverse of `leeway`, subtracting from the validation time.
        ///
        /// Defaults to `0`.
        reject-tokens-expiring-in-less-than: option<u64>,
        /// Whether to validate the `exp` field.
        ///
        /// It will return an error if the time in the `exp` field is past.
        ///
        /// Defaults to `true`.
        validate-exp: option<bool>,
        /// Whether to validate the `nbf` field.
        ///
        /// It will return an error if the current timestamp is before the time in the `nbf` field.
        ///
        /// Validation only happens if `nbf` claim is present in the token.
        /// Adding `nbf` to `required_spec_claims` will make it required.
        ///
        /// Defaults to `false`.
        validate-nbf: option<bool>,
        /// If it contains a value, the validation will check that the `sub` field is the same as the
        /// one provided and will error otherwise.
        ///
        /// Validation only happens if `sub` claim is present in the token.
        /// Adding `sub` to `required_spec_claims` will make it required.
        ///
        /// Defaults to `None`.
        sub: option<string>,
        /// The validation will check that the `alg` of the header is contained
        /// in the ones provided and will error otherwise. Will error if it is empty.
        ///
        /// Defaults to HMAC using SHA-256
        algorithms: option<list<algorithm>>,
    }

    resource validation {
        constructor(jwks: jwks);

        /// Algorithm defaults to HS256
        with-jwks-from: static func(jwks: jwks-source, options: option<validation-options>) -> result<validation, validation-error>;

        set-audience: func(aud: list<string>);
        set-issuer: func(iss: list<string>);
        set-required-spec-claims: func(claims: required-claims);

        decode: func(ctx: borrow<context>) -> result<token-data, validation-error>;
    }

    record validate-props {
        issuer: list<string>,
        audience: list<string>,
        jwks: jwks-source,
        options: option<validation-options>,
    }

    validate: func(ctx: borrow<context>, props: validate-props) -> result<token-data, validation-error>;

    jwt-is-validated: func(ctx: borrow<context>) -> bool;
    get-claims: func(ctx: borrow<context>) -> option<claims>;
}
