/// A lifecycle for client-server connections that ensures proper capability negotiation and state management
///
/// https://modelcontextprotocol.io/specification/2025-06-18/basic/lifecycle
interface lifecycle {
    use types.{initialize-result, context, mcp-error};
    
    /// Handle session initialization
    /// Implementations should declare their capabilities here
    initialize: func(ctx: borrow<context>) -> result<initialize-result, mcp-error>;
}
