interface notifications {
    use wasi:io/streams@0.2.3.{output-stream, stream-error};

    /// https://modelcontextprotocol.io/specification/2025-06-18/server/utilities/logging#log-levels
    @since(version = 0.3.1-alpha.1)
    enum log-level {
        /// Detailed debugging information
        debug,
        /// General informational messages
        info,
        /// Normal but significant events
        notice,
        /// Warning conditions
        warning,
        /// Error conditions
        error,
        /// Critical conditions
        critical,
        /// Action must be taken immediately
        alert,
        /// System is unusable
        emergency,
    }

    enum change {
        tools,
        resources,
        prompts,
    }

    variant update {
        %resource(string),
    }

    /// https://modelcontextprotocol.io/specification/2025-06-18/schema#loggingmessagenotification
    @since(version = 0.3.1-alpha.1)
    record log-message {
        level: log-level,
        logger: option<string>,
        data: list<u8>,
    }

    /// https://www.jsonrpc.org/specification#notification
    record notification {
        method: string,
        params: option<string>,
    }

    /// Log a message to the client.
    @since(version = 0.3.1-alpha.1)
    log: func(output: borrow<output-stream>, message: log-message) -> result<_, stream-error>;

    // Send a JSON-RPC notification to the client.
    @since(version = 0.3.1-alpha.1)
    send: func(output: borrow<output-stream>, notification: notification) -> result<_, stream-error>;

    /// Send a `notifications/*/list_changed` notification to the client.
    send-list-changed: func(output: borrow<output-stream>, change: change) -> result<_, stream-error>;

    /// Send a `notifications/*/updated` notification to the client.
    send-updated: func(output: borrow<output-stream>, update: update) -> result<_, stream-error>;
}
