package wasmcp:transport@0.2.0;

/// Prompts allow servers to provide structured messages and instructions for interacting with language models.
/// Clients can discover available prompts, retrieve their contents, and provide arguments to customize them.
///
/// https://modelcontextprotocol.io/specification/2025-06-18/server/prompts
interface prompts {
    use wasmcp:mcp/mcp-types@0.2.0.{mcp-error};
    use wasmcp:mcp/prompts-types@0.2.0.{list-prompts-request, list-prompts-result, get-prompt-request, get-prompt-result};

    /// List available prompts
    list-prompts: func(request: list-prompts-request) -> result<list-prompts-result, mcp-error>;

    /// Get a specific prompt
    get-prompt: func(request: get-prompt-request) -> result<get-prompt-result, mcp-error>;
}