/// Resources allow servers to share data that provides context to language models, such as files, database schemas, or application-specific information.
/// Each resource is uniquely identified by a URI.
///
/// https://modelcontextprotocol.io/specification/2025-06-18/server/resources
interface resources {
    use types.{list-resources-result, list-resource-templates-result, read-resource-result, context, mcp-error};
    
    /// List available resources
    list-resources: func(ctx: borrow<context>, cursor: option<string>) -> result<list-resources-result, mcp-error>;
    
    /// List resource templates
    list-templates: func(ctx: borrow<context>, cursor: option<string>) -> result<list-resource-templates-result, mcp-error>;
    
    /// Read a specific resource
    read-resource: func(ctx: borrow<context>, uri: string) -> result<read-resource-result, mcp-error>;
}
