/// Tools enable models to interact with external systems, such as querying databases, calling APIs, or performing computations.
/// Each tool is uniquely identified by a name and includes metadata describing its schema.
///
/// https://modelcontextprotocol.io/specification/2025-06-18/server/tools
interface tools {
    use types.{call-tool-result, list-tools-result, context, json, mcp-error};
    
    /// List available tools
    list-tools: func(ctx: borrow<context>, cursor: option<string>) -> result<list-tools-result, mcp-error>;
    
    /// Execute a tool
    call-tool: func(ctx: borrow<context>, name: string, arguments: option<json>) -> result<call-tool-result, mcp-error>;
}
