interface notifications {
    use wasi:io/streams@0.2.3.{output-stream, stream-error};

    /// https://modelcontextprotocol.io/specification/2025-06-18/server/utilities/logging#log-levels
    @since(version = 0.3.1-alpha.1)
    enum log-level {
        /// Detailed debugging information
        debug,
        /// General informational messages
        info,
        /// Normal but significant events
        notice,
        /// Warning conditions
        warning,
        /// Error conditions
        error,
        /// Critical conditions
        critical,
        /// Action must be taken immediately
        alert,
        /// System is unusable
        emergency,
    }

    /// https://modelcontextprotocol.io/specification/2025-06-18/schema#loggingmessagenotification
    @since(version = 0.3.1-alpha.1)
    record log-message {
        level: log-level,
        logger: option<string>,
        data: list<u8>,
    }

    /// https://www.jsonrpc.org/specification#notification
    record notification {
        method: string,
        params: option<string>,
    }

    // Send a JSON-RPC notification to the client.
    @since(version = 0.3.1-alpha.1)
    send: func(output: borrow<output-stream>, notification: notification) -> result<_, stream-error>;

    /// Log a message to the client.
    @since(version = 0.3.1-alpha.1)
    log: func(output: borrow<output-stream>, message: log-message) -> result<_, stream-error>;

    tools-list-changed: func(output: borrow<output-stream>) -> result<_, stream-error>;

    resources-list-changed: func(output: borrow<output-stream>) -> result<_, stream-error>;

    prompts-list-changed: func(output: borrow<output-stream>) -> result<_, stream-error>;

    /// Send a `notifications/resources/updated` notification to the client.
    @since(version = 0.3.1-alpha.1)
    resource-updated: func(output: borrow<output-stream>, uri: string) -> result<_, stream-error>;

    resource notifications {
        constructor(output: output-stream);

        // Send a JSON-RPC notification to the client.
        @since(version = 0.3.1-alpha.1)
        send: func(notification: notification) -> result<_, stream-error>;

        /// Log a message to the client.
        @since(version = 0.3.1-alpha.1)
        log: func(message: log-message) -> result<_, stream-error>;

        tools-list-changed: func() -> result<_, stream-error>;

        resources-list-changed: func() -> result<_, stream-error>;

        prompts-list-changed: func() -> result<_, stream-error>;

        /// Send a `notifications/resources/updated` notification to the client.
        @since(version = 0.3.1-alpha.1)
        resource-updated: func(uri: string) -> result<_, stream-error>;
    }
}
