[package]
name = "otel-trace"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { version = "0.36", features = ["default"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
prost = "0.12"
prost-types = "0.12"
base64 = "0.21"
hex = "0.4"

[build-dependencies]
prost-build = "0.12"

[profile.release]
opt-level = "z"
lto = true
strip = true