name: Release WIT Client Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Client package version (e.g. 0.1.0 or 0.1.0-alpha.1)'
        required: true
        type: string

jobs:
  release:
    name: Release Client Package
    uses: ./.github/workflows/reusable-release-wit.yml
    with:
      package-name: client
      version: ${{ inputs.version }}
      wit-dir: wit/client
      wkg-package: wasmcp:client
      tag-prefix: client-v
    secrets: inherit
