name: Release HTTP Transport

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Component version (e.g. 0.1.0 or 0.1.0-beta.2)'
        required: true
        type: string

jobs:
  release:
    name: Release HTTP Transport
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/reusable-release-component.yml
    with:
      component-name: http-transport
      component-crate: http-transport
      version: ${{ inputs.version }}
      wkg-package: wasmcp:http-transport
      tag-prefix: http-transport-v
    secrets: inherit
