name: Release WIT MCP Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'MCP package version (e.g. 0.1.0 or 0.1.0-alpha.1)'
        required: true
        type: string
      protocol-version:
        description: 'MCP protocol version (e.g. 2025-06-18)'
        required: true
        type: string
        default: '2025-06-18'

jobs:
  release:
    name: Release MCP Package
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/reusable-release-wit.yml
    with:
      package-name: mcp-v${{ inputs.protocol-version }}
      version: ${{ inputs.version }}
      wit-dir: spec/${{ inputs.protocol-version }}/wit
      wkg-package: wasmcp:mcp-v${{ inputs.protocol-version }}
      tag-prefix: mcp-v${{ inputs.protocol-version }}-v
    secrets: inherit
