[package]
name = "{{ package_name }}"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen = "0.34"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]
